/* Generated by cbindgen - DO NOT EDIT MANUALLY */

#ifndef DOCUMENT_INTELLIGENCE_ENGINE_H
#define DOCUMENT_INTELLIGENCE_ENGINE_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque engine instance handle.
 */
typedef struct DIEEngineHandle DIEEngineHandle;

/**
 * Asynchronous progress callback invoked during optical and neural stages.
 */
typedef void (*DIEProgressCallback)(const char *event_type,
                                    int32_t current_page,
                                    int32_t total_pages,
                                    const char *payload_json,
                                    void *user_data);

/**
 * Initialize a new Document Intelligence Engine instance.
 *
 * # Safety
 * If `models_dir` or `config_json` are non-null, they must point to valid,
 * null-terminated C strings.
 */
struct DIEEngineHandle *die_engine_init(const char *_models_dir, const char *_config_json);

/**
 * Destroy an engine instance and reclaim allocated resources.
 *
 * # Safety
 * `handle` must be a valid pointer returned by [`die_engine_init`], or null.
 */
void die_engine_destroy(struct DIEEngineHandle *handle);

/**
 * Pass 1: Ingest and process an assessment page image capture.
 *
 * # Safety
 * - `handle` must point to a valid [`DIEEngineHandle`].
 * - `session_id`, `section_id` must point to valid null-terminated C strings.
 * - `image_bytes` must point to a valid byte array of at least `image_len` bytes.
 */
int32_t die_session_ingest_page(struct DIEEngineHandle *handle,
                                const char *session_id,
                                const char *section_id,
                                int32_t page_num,
                                const uint8_t *image_bytes,
                                uintptr_t image_len,
                                DIEProgressCallback callback,
                                void *user_data);

/**
 * Pass 2: Reconcile session questions and export into requested format.
 *
 * Returns a newly allocated null-terminated C string on success, or null on error.
 * Caller MUST free the returned string using [`die_string_free`].
 *
 * # Safety
 * - `handle` must point to a valid [`DIEEngineHandle`].
 * - `session_id`, `target_format` must point to valid null-terminated C strings.
 */
char *die_session_export(struct DIEEngineHandle *handle,
                         const char *session_id,
                         const char *target_format);

/**
 * Free a string previously allocated by [`die_session_export`].
 *
 * # Safety
 * `ptr` must be a pointer returned by [`die_session_export`], or null.
 */
void die_string_free(char *ptr);

#endif /* DOCUMENT_INTELLIGENCE_ENGINE_H */
